name: Advanced CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [18]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: /home/craghu/Desktop/github/actions-runner/runner/actin_dev/actin_dev/package-lock.json

      - name: Run tests
        run: npm test
        working-directory: /home/craghu/Desktop/github/actions-runner/runner/actin_dev/actin_dev/package-lock.json
        env:
          CI: true

  lint:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Lint code
        run: npm run lint
        working-directory: /home/craghu/Desktop/github/actions-runner/runner/actin_dev/actin_dev/package-lock.json

  deploy:
    runs-on: self-hosted
    needs: [build, lint]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy application
        env:
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          echo "Deploying application with token $API_TOKEN"
          
