name: Docker CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  build-and-publish:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: |
          chmod +x startJenkinsSlave2004.sh
          ./startJenkinsSlave2004.sh

      - name: Tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/actin_dev:latest
          docker tag actin_dev:latest $IMAGE_NAME

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/${{ github.repository_owner }}/actin_dev:latest
          docker push $IMAGE_NAME
